### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by encukou** [PyConPL/Book#20]
What is the license for this repository?

How can I use the information here?

If I contribute, how will you use the contribution? Are contributions considered exclusive to the PyCon PL book?

It would be nice if this information was added to the repo.

**Comment by fk-lx** [comment]
License for the PyCon PL 2015 book articles is CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0) and has been added in 2015 directory. Thanks for reporting this issue.
