### ISSUE TITLE
Hacking Micropython issue

### ISSUE THREAD

**Issue by APOON24** [PyConPL/Book#62]
Hello guy,

I'm working on micropython and it's super interesting. 
I have project and I would like to create my own python module. I saw your article and by the way for this. It's super useful. https://github.com/PyConPL/Book/blob/master/2016/workshops/hacking_micropython/text.md

I just copy paste your code but when I try to compile there is a issue. the compiler says 
mymodule.c:21:5: error: unknown field 'name' specified in initializer
     .name = MP_QSTR_mymodule,
     ^
mymodule.c:21:5: error: initialization makes pointer from integer without a cast [-Werror]
mymodule.c:21:5: error: (near initialization for 'mp_module_mymodule.globals') [-Werror]
cc1: all warnings being treated as errors

Do you have an idea of my issue ?

Thank you in advance

**Comment by kwadrat** [comment]
Good Morning! What is your e-mail? Please answer to mine: ciri@ciri.pl
I will try to connect you with author of this text, Radomir.

Best wishes,
Piotr Kasprzyk

**Comment by kwadrat** [comment]
@deshipu ^^^ I think you could help with this issue. Thank you very much! Best wishes, Piotr Kasprzyk

**Comment by kwadrat** [comment]
The issue was solved by e-mail.
