### ISSUE TITLE
Github does not serve SVG

### ISSUE THREAD

**Issue by clozinski** [PyConPL/Book#66]
From StackOverflow:
https://stackoverflow.com/questions/13808020/include-an-svg-hosted-on-github-in-markdown

One person writes:
 >> I contacted GitHub to say that github.io-hosted SVGs are no longer displayed in GitHub READMEs. 

He received this reply:

>We have had to disable svg image rendering on GitHub.com due to potential cross site scripting vulnerabilities.
__________
It is best to use a relative link, but that is not supported anymore. 
One could use a site that mirrors github, but that breaks when my merge request is accepted and my version of the repository is deleted. 

I tried hosting from my site.  That also did not work. 
So my directory includes the svg image, but the README.md file does not link to it. 

What am I going to do?  Whatever the recommendation is.  This is not just my problem.  Anyone with images will have the same problem. 

And thank you to all of the volunteers organizing this. 

Warm Regards
Chris

**Comment by kwadrat** [comment]
Image rendering on GitHub is useful but not required - we are going to generate PDF from these files.

Best wishes,
Piotr
